# Generated by Django 6.0.1 on 2026-01-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myshop", "0003_alter_product_available_alter_product_created_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="myshop_prod_id_2e6696_idx",
            old_fields=("id", "slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
